# Generated by Django 6.0.3 on 2026-04-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, help_text='อาการเบื้องต้น/เหตุผลที่นัดหมาย', max_length=200),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='การวินิจฉัยโรค'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='อุณหภูมิ (°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='น้ำหนัก (kg)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionline',
            name='dosage',
            field=models.CharField(blank=True, help_text='วิธีใช้ (Dosage)', max_length=200),
        ),
    ]
