# Generated by Django 4.2.29 on 2026-04-06 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic_api', '0002_appointment_reason_medicalrecord_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('medicine', 'ยาเม็ด/ยาน้ำ'), ('vaccine', 'วัคซีน'), ('supply', 'เวชภัณฑ์'), ('food', 'อาหารสัตว์'), ('accessory', 'อุปกรณ์/ปลอกคอ'), ('other', 'อื่นๆ')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ราคาต้นทุนต่อหน่วย', max_digits=10),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='exam_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ค่าตรวจรักษา', max_digits=10),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='payment_method',
            field=models.CharField(blank=True, help_text='เงินสด, โอนเงิน, บัตรเครดิต', max_length=50),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='allergies',
            field=models.TextField(blank=True, help_text='ประวัติแพ้ยา/อาหาร'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_neutered',
            field=models.BooleanField(default=False, help_text='ทำหมันแล้วหรือไม่'),
        ),
        migrations.AddField(
            model_name='pet',
            name='markings',
            field=models.TextField(blank=True, help_text='ตำหนิ/จุดสังเกต'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, help_text='เพศ', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prescriptionline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (รอยืนยัน)'), ('confirmed', 'Confirmed (ยืนยันแล้ว)'), ('waiting', 'Waiting (กำลังรอตรวจ)'), ('examining', 'Examining (กำลังตรวจ)'), ('payment', 'Payment (รอชำระเงิน)'), ('completed', 'Completed (เสร็จสิ้น)'), ('cancelled', 'Cancelled (ยกเลิก)')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='ราคาขายต่อหน่วย', max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vet', 'Veterinarian'), ('assistant', 'Assistant')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
